app:
  name: example-app
  namespace: example
  version: "1.0.0"
  lifecycle: StatefulSet
  replicaCount: 2
  listenPort: 80
  metricsPort: 3001


serviceAccount:
  create: true
  name: example-sa

service:
  enabled: true
  type: ClusterIP

ingress:
  - name: example-app-default
    host: example.io
    path: 
      - /v1
    className: nginx

pod:
  restartPolicy: Always
  terminationGracePeriodSecs: 30
  container:
    repository: nginxdemos/hello
    tag: 0.4
    pullPolicy: IfNotPresent
    volumeMounts:
      - name: nginx-cache
        mountPath: /var/cache/nginx
      - name: nginx-run
        mountPath: /var/run
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: 80
        scheme: HTTP
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 5
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: 80
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
  volumes:
    - name: nginx-cache
      emptyDir: {}
    - name: nginx-run
      emptyDir: {}