{{- if and .Values.pod .Values.pod.autoscaling .Values.pod.autoscaling.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "helper.chartName" . }}-hpa
  namespace: {{ include "helper.namespace" . }}
  labels:
    {{- include "helper.labels" . | nindent 4 }}
    {{- with .Values.pod.autoscaling.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.pod.autoscaling.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "helper.chartName" . }}-deployment
  {{- if .Values.pod.autoscaling.minReplicas }}
  minReplicas: {{ .Values.pod.autoscaling.minReplicas }}
  {{- end }}
  {{- if .Values.pod.autoscaling.maxReplicas }}
  maxReplicas: {{ .Values.pod.autoscaling.maxReplicas }}
  {{- end }}
  metrics:
    {{- if .Values.pod.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.pod.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.pod.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.pod.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
