{{- if and .Values.rbac .Values.rbac.role .Values.rbac.role.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "helper.chartName" . }}-role
  namespace: {{ include "helper.namespace" . }}
  labels:
    {{- include "helper.labels" . | nindent 4 }}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    {{- with .Values.rbac.role.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.rbac.role.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  {{- if or (not (hasKey .Values.rbac.role "defaultRule")) (eq .Values.rbac.role.defaultRule true) }}
  - apiGroups: [""] # "" indicates the core API group
    resources: ["configmaps", "secrets"]
    verbs: ["get", "watch", "list"]
  {{- end }}
  {{- with .Values.rbac.role.extraRules }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
