{{- if .Values.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helper.chartName" . }}-secret
  namespace: {{ include "helper.namespace" . }}
  labels:
    {{- include "helper.labels" . | nindent 4 }}
    {{- with .Values.secrets.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.secrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
{{- with .Values.secrets.values }}
  {{- range $key, $val := . }}
  {{ $key }}: {{ tpl ($val | toString) $ | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
